//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMS_SCHEDULE
    {
        public int Id { get; set; }
        public int ID_STUDENT { get; set; }
        public int ID_COURSE { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string COURSE_NAME { get; set; }
        public Nullable<int> CLASS_NUMBER { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
