//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAdvisor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitAdvisorDBEntities1 : DbContext
    {
        public FitAdvisorDBEntities1()
            : base("name=FitAdvisorDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<INSTRUCTOR> INSTRUCTORs { get; set; }
        public virtual DbSet<INSTRUCTOR_COURSE> INSTRUCTOR_COURSE { get; set; }
        public virtual DbSet<MESSAGE> MESSAGEs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDENT_COURSE> STUDENT_COURSE { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<COMMUNITY_SERVICE> COMMUNITY_SERVICE { get; set; }
        public virtual DbSet<EXAMS_SCHEDULE> EXAMS_SCHEDULE { get; set; }
        public virtual DbSet<HOMEWORK> HOMEWORK { get; set; }
        public virtual DbSet<NOTE> NOTEs { get; set; }
    }
}
