//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR_COURSE
    {
        public int ID { get; set; }
        public Nullable<int> ID_INSTRUCTOR { get; set; }
        public Nullable<int> ID_COURSE { get; set; }
        public string INSTRUCTOR_NOTE { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
    }
}
