//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public int Id { get; set; }
        public string NOTES { get; set; }
        public System.DateTime TIME { get; set; }
        public int ID_INSTRUCTOR { get; set; }
        public int ID_STUDENT { get; set; }
    
        public virtual INSTRUCTOR INSTRUCTOR { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
