//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAdvisor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_COURSE
    {
        public int ID { get; set; }
        public Nullable<int> ID_STUDENT { get; set; }
        public Nullable<int> ID_COURSE { get; set; }
        public int MAEKS { get; set; }
        public Nullable<int> ABSSENCE { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
